code --install-extension budparr.language-hugo-vscode --force &
code --install-extension dsznajder.es7-react-js-snippets --force &
code --install-extension eamodio.gitlens --force &
code --install-extension esbenp.prettier-vscode --force &
code --install-extension hashicorp.terraform --force &
code --install-extension Infracost.infracost --force &
code --install-extension mervin.markdown-formatter --force &
code --install-extension ms-azuretools.vscode-docker --force &
code --install-extension ms-python.black-formatter --force &
code --install-extension ms-python.python --force &
code --install-extension ms-python.vscode-pylance --force &
code --install-extension ms-toolsai.jupyter --force &
code --install-extension ms-toolsai.jupyter-keymap --force &
code --install-extension ms-toolsai.jupyter-renderers --force &
code --install-extension ms-vscode.makefile-tools --force &
code --install-extension ms-vscode.sublime-keybindings --force &
code --install-extension ms-vsliveshare.vsliveshare --force &
code --install-extension ms-vsliveshare.vsliveshare-audio --force &
code --install-extension ms-vsliveshare.vsliveshare-pack --force &
code --install-extension oliversturm.fix-json --force &
code --install-extension redhat.vscode-yaml --force &
code --install-extension rickynormandeau.mariana-pro --force &
code --install-extension tamasfe.even-better-toml --force &
code --install-extension tomoki1207.pdf --force &
code --install-extension wholroyd.jinja --force &
code --install-extension yzhang.markdown-all-in-one --force
