code --install-extension Bar.python-import-helper --force &
code --install-extension bradlc.vscode-tailwindcss --force &
code --install-extension budparr.language-hugo-vscode --force &
code --install-extension charliermarsh.ruff --force &
code --install-extension christian-kohler.npm-intellisense --force &
code --install-extension ctf0.htmlhint --force &
code --install-extension dsznajder.es7-react-js-snippets --force &
code --install-extension dzannotti.vscode-babel-coloring --force &
code --install-extension eamodio.gitlens --force &
code --install-extension esbenp.prettier-vscode --force &
code --install-extension exiasr.hadolint --force &
code --install-extension formulahendry.auto-rename-tag --force &
code --install-extension GitHub.copilot --force &
code --install-extension GitHub.copilot-chat --force &
code --install-extension github.vscode-github-actions --force &
code --install-extension GitHub.vscode-pull-request-github --force &
code --install-extension golang.go --force &
code --install-extension hashicorp.terraform --force &
code --install-extension Infracost.infracost --force &
code --install-extension janisdd.vscode-edit-csv --force &
code --install-extension johnpapa.vscode-peacock --force &
code --install-extension kolo.kolo --force &
code --install-extension kumar-harsh.graphql-for-vscode --force &
code --install-extension lextudio.restructuredtext --force &
code --install-extension mechatroner.rainbow-csv --force &
code --install-extension mervin.markdown-formatter --force &
code --install-extension mhutchie.git-graph --force &
code --install-extension ms-azuretools.vscode-docker --force &
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools --force &
code --install-extension ms-python.black-formatter --force &
code --install-extension ms-python.isort --force &
code --install-extension ms-python.python --force &
code --install-extension ms-python.vscode-pylance --force &
code --install-extension ms-toolsai.jupyter --force &
code --install-extension ms-toolsai.jupyter-keymap --force &
code --install-extension ms-toolsai.jupyter-renderers --force &
code --install-extension ms-toolsai.vscode-jupyter-cell-tags --force &
code --install-extension ms-toolsai.vscode-jupyter-slideshow --force &
code --install-extension ms-vscode-remote.remote-containers --force &
code --install-extension ms-vscode-remote.remote-ssh --force &
code --install-extension ms-vscode-remote.remote-ssh-edit --force &
code --install-extension ms-vscode-remote.remote-wsl --force &
code --install-extension ms-vscode.makefile-tools --force &
code --install-extension ms-vscode.remote-explorer --force &
code --install-extension ms-vscode.sublime-keybindings --force &
code --install-extension ms-vsliveshare.vsliveshare --force &
code --install-extension ms-vsliveshare.vsliveshare-audio --force &
code --install-extension ms-vsliveshare.vsliveshare-pack --force &
code --install-extension njpwerner.autodocstring --force &
code --install-extension oliversturm.fix-json --force &
code --install-extension pnp.polacode --force &
code --install-extension pranaygp.vscode-css-peek --force &
code --install-extension redhat.vscode-yaml --force &
code --install-extension rickynormandeau.mariana-pro --force &
code --install-extension ritwickdey.LiveServer --force &
code --install-extension tamasfe.even-better-toml --force &
code --install-extension TatsuyaNakamori.resttext --force &
code --install-extension tht13.rst-vscode --force &
code --install-extension tomoki1207.pdf --force &
code --install-extension trond-snekvik.simple-rst --force &
code --install-extension wholroyd.jinja --force &
code --install-extension wix.vscode-import-cost --force &
code --install-extension yzhang.markdown-all-in-one --force
